export const restaurantList = [
  {
    id: 1,
    name: "McDonald's",
    cuisines: ["American", "Burgers", "Fast Food"],
    avgRating: 4.2,
    deliveryTime: "25-30 mins",
    costForTwo: "₹400 for two",
    bgColor: "#DA291C",
  },
  {
    id: 2,
    name: "Pizza Hut",
    cuisines: ["Pizza", "Italian", "Fast Food"],
    avgRating: 4.0,
    deliveryTime: "30-35 mins",
    costForTwo: "₹600 for two",
    bgColor: "#EE3124",
  },
  {
    id: 3,
    name: "KFC",
    cuisines: ["Chicken", "Burgers", "American"],
    avgRating: 4.3,
    deliveryTime: "20-25 mins",
    costForTwo: "₹500 for two",
    bgColor: "#F40027",
  },
  {
    id: 4,
    name: "Domino's Pizza",
    cuisines: ["Pizza", "Pasta", "Desserts"],
    avgRating: 4.1,
    deliveryTime: "25-30 mins",
    costForTwo: "₹550 for two",
    bgColor: "#006491",
  },
  {
    id: 5,
    name: "Subway",
    cuisines: ["Healthy", "Sandwiches", "Salads"],
    avgRating: 3.9,
    deliveryTime: "20-25 mins",
    costForTwo: "₹350 for two",
    bgColor: "#009639",
  },
  {
    id: 6,
    name: "Burger King",
    cuisines: ["Burgers", "American", "Fries"],
    avgRating: 4.0,
    deliveryTime: "30-35 mins",
    costForTwo: "₹450 for two",
    bgColor: "#F5821F",
  },
  {
    id: 7,
    name: "Biryani Blues",
    cuisines: ["Biryani", "North Indian", "Mughlai"],
    avgRating: 4.5,
    deliveryTime: "35-40 mins",
    costForTwo: "₹700 for two",
    bgColor: "#8B4513",
  },
  {
    id: 8,
    name: "Haldiram's",
    cuisines: ["North Indian", "Chinese", "Sweets"],
    avgRating: 4.4,
    deliveryTime: "30-35 mins",
    costForTwo: "₹500 for two",
    bgColor: "#FF6B00",
  },
];

export const LOGO_URL =
  "https://mir-s3-cdn-cf.behance.net/project_modules/hd/25539c29532269.55f7d6a0a8c71.jpg";
